[theme]
theme = "slick"
[theme.overrides]
separator = " "
separator_bg = "#00000000"
idle_bg = "#4f4f4f"
idle_fg = "#ffffff"

[icons]
icons = "material-nf"

[[block]]
block = "sound"
driver = "pulseaudio"
show_volume_when_muted = true
format = " $volume $icon "

[[block]]
block="backlight"
device="intel_backlight"
format=" $brightness $icon "

[[block]]
block="net"
device="wlp1s0"
format=" $ssid at $signal_strength $icon "

[[block]]
block = "memory"
interval = 5
format = "$mem_total_used / $mem_total $icon "
format_alt = "$mem_total_used_percents $icon "

[[block]]
block = "battery"
interval = 5
format = " $percentage $icon "
full_format = " :D $icon "
empty_format = " D: $icon "
not_charging_format = " $percentage $time $icon "
good = 50
warning = 20
critical = 10
full_threshold = 95
empty_threshold = 5

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%r') $icon "
[block.theme_overrides]
idle_bg = "#4f4f4f"
