icons_format = "{icon}"

[theme]
theme = "space-villain"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#ffffff"

[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon: $volume "
show_volume_when_muted = true

[[block]]
block="backlight"
device="intel_backlight"
format=" $icon: $brightness "
[block.theme_overrides]
idle_bg = "#FFFFFF"
idle_fg = "#000000"

[[block]]
block = "memory"
interval = 1
format = " $icon: $mem_total_used / $mem_total "
format_alt = "$icon: $mem_total_used_percents"

[[block]]
block = "battery"
interval = 5
format = " $icon: $percentage "
full_format = " $icon: :D "
empty_format = " $icon: D: "
not_charging_format = " $icon: $percentage $time "
good = 50
warning = 20
critical = 10
full_threshold = 95
empty_threshold = 5

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%r') "
[block.theme_overrides]
idle_bg = "#505050"
